version: '3.8'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    volumes:
#      - ./emoji_predictor/app:/app
#      - ./emoji_predictor/models:/app/models
    #command: uvicorn ./emoji_predictor/app/RNN_FastAPI:app --host 0.0.0.0 --port 8000 --reload
